### ISSUE TITLE
v2.0.0 published to npm is missing dist/ directory

### ISSUE THREAD

**Issue by asteinarson** [hjdhjd/esphome-client#6]
### esphome-client

v 2.0.0

### Describe the problem

Hi @hjdhjd!

Thanks for the great work on v2.0.0.

It looks like the published package on npm is missing the compiled dist/ directory (and src/ is not there), causing TS2307: Cannot find module 'esphome-client' when installed via npm or pnpm.

Root Cause:
In package.json, "postpublish": "npm run clean" runs after npm publish finishes, but because there is no explicit "files": ["dist"] field defined in package.json, the tarball published to the npm registry is missing build artifacts.

Suggested Fix:
Add "files": ["dist"] to package.json so npm publish explicitly bundles the built dist/ folder into the published artifact payload, or remove the postpublish clean step.

### Relevant log output

```shell
$ ls node_modules/esphome-client/
# No <dist> or <src> folder below
LICENSE.md  node_modules  package.json  README.md
```

**Comment by hjdhjd** [comment]
Thanks for the kind words. The published package is intact. I pulled the v2.0.0 tarball directly from the npm registry to double-check: the complete dist/ tree is there, 232 compiled files including dist/index.js and the type declarations.

This package is in active use across several other consumers...so it works and imports correctly. I'm going to presume that you used AI to generate some portion of the above...I suspect it's hallucinating. 😄 

postpublish runs after the tarball has been created and uploaded, so it can't touch what gets published. And a files field isn't needed because .npmignore already does that job as an explicit allowlist - ignore everything, then include LICENSE.md, README.md, dist/**, and package.json.

**Comment by asteinarson** [comment]
I tried today anew - and it worked flawlessly this time. 

You're right, in my ticket  - the explanation "why" files were missing came from Gemini. 

I don't know why the "dist" folder was missing the first time.
